name: Miri
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  miri:
    name: Miri (Undefined Behavior Detection)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - uses: Swatinem/rust-cache@v2

      - name: Run Miri
        run: cargo +nightly miri test --all-targets --all-features
        env:
          MIRIFLAGS: "-Zmiri-strict-provenance"

      - name: Run Miri with Symbolic Alignment Check
        run: cargo +nightly miri test --all-targets --all-features
        env:
          MIRIFLAGS: "-Zmiri-strict-provenance -Zmiri-symbolic-alignment-check"